package edu.utsa.cs3443.dalaapp;

import com.idktogo.idk_to_go.core.Navigation;
import com.idktogo.idk_to_go.dao.UserDAO;
import com.idktogo.idk_to_go.model.User;
import javafx.application.Platform;
import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.concurrent.CompletableFuture;

public class SignUpController {

    @FXML private TextField usernameField;
    @FXML private TextField emailField;
    @FXML private TextField firstNameField;
    @FXML private TextField lastNameField;
    @FXML private PasswordField passwordField;

    @FXML
    private void handleRegister() {
        String username = usernameField.getText().trim();
        String email = emailField.getText().trim();
        String firstName = firstNameField.getText().trim();
        String lastName = lastNameField.getText().trim();
        String password = passwordField.getText().trim();

        if (username.isEmpty() || email.isEmpty() || password.isEmpty()) {
            showAlert("Missing Fields", "Please fill out all required fields (username, email, password).");
            return;
        }

        UserDAO.findByUsername(username)
                .thenCompose(optionalUser -> {
                    if (optionalUser.isPresent()) {
                        Platform.runLater(() -> showAlert("Error", "Username is already taken."));
                        return CompletableFuture.completedFuture(null);
                    }

                    return UserDAO.findByEmail(email)
                            .thenCompose(optionalEmail -> {
                                if (optionalEmail.isPresent()) {
                                    Platform.runLater(() -> showAlert("Error", "Email is already taken."));
                                    return CompletableFuture.completedFuture(null);
                                }


                                User newUser = new User(
                                        0,                      // auto-generated by DB
                                        username,
                                        email,
                                        firstName,
                                        lastName,
                                        password,
                                        false,                  // isAdmin default
                                        Timestamp.from(Instant.now())
                                );

                                return UserDAO.create(newUser)
                                        .thenRun(() -> Platform.runLater(() -> {
                                            showAlert("Success", "Registration successful! Redirecting to login...");
                                            goToLogin();
                                        }));
                            });
                })
                .exceptionally(ex -> {
                    Platform.runLater(() -> showAlert("Error", "Registration failed: " + ex.getMessage()));
                    return null;
                });
    }

    @FXML
    private void goToLogin() {
        Navigation.load("/com/idktogo/idk_to_go/login.fxml");
    }

    private void showAlert(String title, String message) {
        Alert alert = new Alert(Alert.AlertType.INFORMATION);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }
}